### ISSUE TITLE
Tool documentation missing a few key pieces of information

### ISSUE THREAD

**Issue by banool** [sentioxyz/typemove#52]
Hey hey!

I'm finally trying this tool out but I'm having some issues. Let me list out some potential improvements:
1. The tool relies on prettier but requires the user to install it themselves.
2. The tool doesn't work with bun (though that might be the fault of bun).
3. I can't figure out how to generate code based on a local compilation. The README says `path-of-entry-abi-file` but I've tried my source code, build directory, `build/blah/abis/blah/`, etc. and nothing ever gets generated.
4. If nothing gets generated, that should maybe be an error in the tool.
5. The only options it mentions for networks are testnet and mainnet, it'd be great if devnet and local were also supported.

**Comment by zfy0701** [comment]
1. fixed
2. will take a look later on
3. the command line get reworked, please checkout the [doc](https://github.com/sentioxyz/typemove/blob/main/packages/aptos/Readme.md#code-generation) or use `--help`, if it doesn't work, could you upload the content `build/blah/abis/blah/` so we could take a look why it's broken?
4. done
5. done, now `--network` could take an URL, you could find example [here](https://github.com/sentioxyz/typemove/blob/main/packages/aptos/Readme.md#code-generation)
