### ISSUE TITLE
Entry functions not included in builder for codegen (SUI)

### ISSUE THREAD

**Issue by nithilan4** [sentioxyz/typemove#75]
Hi, I noticed that when I ran codegen on my package, the entry functions weren't in the builder namespace of my modules.
`public fun stake` shows up, but `entry fun stake_to_sender` does not show up, even though both are callable in a txb.

**Comment by zfy0701** [comment]
what's your package address?

**Comment by nithilan4** [comment]
I'm sorry, I can't share it :(. But if you make an entry function but don't put public on it, it's still callable in txbs but not to other modules and that's when it doesn't show up.

#77 seems to do the trick for my contract. I'm not sure if this introduces an issue by allowing all entry functions to be in the builder namespace for codegen regardless of visibility though.
