### ISSUE TITLE
Codegen on packages with a leading 0 have incorrect TYPE_QNAME for objects on SUI

### ISSUE THREAD

**Issue by nithilan4** [sentioxyz/typemove#76]
When I generated a codegen for package:
`0x02dab35...`
The corresponding TYPE_QNAME for all objects within it included
`0x2dab354..`, which is missing the leading 0.

I explored a little bit and the issue seems to actually be within the SuiClient, where calling
`await suiClient.getNormalizedMoveModulesByPackage({ package: "0x02dab35..." })` returned an ABI where all the addresses had the incorrect `0x2dab354...`.

**Comment by nithilan4** [comment]
I've created an issue on the Sui repo here: https://github.com/MystenLabs/sui/issues/16083

**Comment by zfy0701** [comment]
yeah, there are a lot of inconsistent for this

I think the rule here is for type name, it's always without leading zero, e.g. you will see `0x1::xx::yy`, not `0x000....01::xx::yy`
and in the context of address, then it's always have leading zero

**Comment by nithilan4** [comment]
interesting, thanks for explaining. feel free to close if you want.
